---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-50-2
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/**/*
