AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/AccessModifierIndentation:
  Enabled: true

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/OptionalBooleanParameter:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: true
  EnforcedStyle: verbose

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: false
