require:
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 25

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/OptionalBooleanParameter:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: true
  EnforcedStyle: verbose

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: false
