language: ruby
rvm:
  - 2.6.6
cache: bundler
before_install: gem install bundler -v 2.2.23
addons:
  code_climate:
    repo_token:
      secure: "fAeU8/IbTBWoigiXQ9ayNskYEtRvuCfrH97PcGs2GBrJ60bVbkyfD71aOhMfriQM58FvjnpyKuaW+anT80m4Z7+aO7WKlTrL9vXqANHaV6IsjrsyJNgKYpZZjXwpEqXyLPqZ6pwLoyg1Oi+ViApbLLmVoJLH4hdo/Nn9swBUVdhvJXTVobhOsoUri/kACLH/1A9BvwWn/gss1fBAQAzx53nvLKzCq7fFkVjwV45oJFGnYSnDDpUY9UNbv/4kxG81ylbgtDnUAM3nmiD2GyPBSh2sOkXqNLYBb77X7kxWrRLxGMM+mF3DtdFpfkF3q49R2W9jktIEJVNVhAGH3tZ9Y21KSjcaPm+0YgILUodqjn21Til2XK4oGAvsD6DJBgA6qdDltii2s9XUXhCxUzvDtYolDDfrhsqyK1py/RIrWbmkIgE5mGiUUfMMyCuxaQLPNskbHxDrBqnsYPLf1luab0XYI1ySD9As2iFyxU2E+Y9QtHsbdXko04ErOMlDnVPRK+CSk+Va6eF4y+lVihpVM59CtArRVNf6MC33Qnpt6AEgJMHUm+C8g3cPsCwtjmU/AeI0oPvjzP78FXBqITrMC+9PPCL3Np0zpXGvvdUmjtWpMYJDEkraQsGWJrF3/MD1iUaelkNGDxRDHIkIxq/pHA6dwEhGNIOJQ9HGntobD3M="
after_success:
  - bundle exec codeclimate-test-reporter
