language: ruby
rvm:
  - 2.7.2
before_install: gem install bundler -v 2.2.23
addons:
    code_climate:
        repo_token: 8e4f3d6c483544a1479af37a53ca72b968cf77cdf7a050e3e163cf526444d832
after_success:
  - bundle exec codeclimate-test-reporter
